version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/node
      
jobs:
  my-job-name:
    environment:
      testenv: setbyme_testenv
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          npm install && npx cypress run

workflows:
  my-custom-workflow:
    jobs:
      - my-job-name
