version: 2.1
orbs:
  cypress: cypress-io/cypress@1.29.0

workflows:
    example-workflow:
      jobs:
        - cypress/run:
            context: cypress_keys_temp 
            record: true
            store_artifacts: true
