# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, feat-report]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using node version 12
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i
    - run: npx cypress run
    

    - name: Export mochawesome report
      if: always()
      run: |
        node --version       
        npm run merge_reports         
        echo "LS mocha dir"
        ls /tmp/cypress/reports/mocha
        echo "pwd"
        pwd
