# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master, feat-report]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using node version 12
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm i
    - run: npx cypress run
    

    - name: Export mochawesome report
      if: always()
      run: |
        node --version       
        node_modules/.bin/mochawesome-merge --reportDir /tmp/cypress/reports/mocha/*.json > /tmp/cypress/reports/mocha/output.json
        node_modules/.bin/marge /tmp/cypress/reports/mocha/output.json --reportDir /tmp/cypress/reports/mocha   
        ls /tmp/cypress/reports/mocha
        cat /tmp/cypress/reports/mocha/output.html

    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: Report
        path: '/tmp/cypress/reports/mocha'
        if-no-files-found: ignore