# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Using node version 12
      uses: actions/setup-node@v2
      with:
        node-version: 12.x
        cache: 'npm'
    - run: npm i
    - run: npx cypress run
    
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout V2"
        uses: actions/checkout@v2
      - name: SETUP NODE
        uses: actions/setup-node@v2
      - name: RUNNING SHELL COMMANDS
        run: |
          echo This is a simeplemessage
          echo $SHELL
          pwd
          ls
          echo "end"
 
